spring:
  application:
    name: traveller-guide-api

server:
  forward-headers-strategy: framework

traveller-guide:
  security:
    api-key:
      header-name: X-API-Key
      value: ${TRAVELLER_GUIDE_API_KEY}
      enforce-https: true
